### PR TITLE
Fix parsed document as nil for other formats

### LINKED ISSUE #177: GitHub sync fail - nil.top_of_the_file_comment/0 is undefined
Hello,

I use latest Docker image (1.5.0). I setup GitHub accent integration. I added webhook to GitHub. Sync via CLI works without any issues. After receiving a notification from GitHub, I receive error messages in the logs:

```
accent         | 06:31:54.089 [info] Running Accent.Endpoint with cowboy 2.7.0 at 0.0.0.0:4000 (http)
accent         | 06:31:54.090 [info] Access Accent.Endpoint at http://localhost:4000
accent         | 06:32:27.620 request_id=Fgxcv9n62IwwCUwAAAJh [info] POST /hooks/github
accent         | 06:32:27.672 request_id=Fgxcv9n62IwwCUwAAAJh [info] Sent 204 in 51ms
accent         | 06:32:28.502 [error] GenServer #PID<0.4910.0> terminating
accent         | ** (UndefinedFunctionError) function nil.top_of_the_file_comment/0 is undefined
accent         |     nil.top_of_the_file_comment()
accent         |     (accent) lib/hook/consumers/github/sync.ex:55: Accent.Hook.Consumers.GitHub.Sync.build_context/4
accent         |     (elixir) lib/enum.ex:1336: Enum."-map/2-lists^map/1-0-"/2
accent         |     (elixir) lib/enum.ex:2994: Enum.flat_map_list/2
accent         |     (accent) lib/hook/consumers/github/sync.ex:15: Accent.Hook.Consumers.GitHub.Sync.persist/6
accent         |     (accent) lib/hook/consumers/github.ex:43: Accent.Hook.Consumers.GitHub.sync_and_add_translations/4
accent         |     (elixir) lib/enum.ex:783: Enum."-each/2-lists^foreach/1-0-"/2
accent         |     (elixir) lib/enum.ex:783: Enum.each/2
accent         | Last message: {:"$gen_consumer", {#PID<0.4909.0>, #Reference<0.1305960628.696778753.74429>}, [%Accent.Hook.Context{event: "", payload: %{default_ref: "master", ref: "refs/heads/master", repository: "ad-m/test-accent", token: "60d623b2d17a10898f7337bffa78139a33ca6590"}, project: %Accent.Project{__meta__: #Ecto.Schema.Metadata<:loaded, "projects">, collaborators: #Ecto.Association.NotLoaded<association :collaborators is not loaded>, conflicts_count: :not_loaded, id: "dfa929d1-fd8c-4451-a00d-aaaffa63f825", inserted_at: ~U[2020-05-05 11:25:55.000000Z], integrations: #Ecto.Association.NotLoaded<association :integrations is not loaded>, language: #Ecto.Association.NotLoaded<association :language is not loaded>, language_id: "b7222eaf-65e1-4f78-94b6-b388e32c46d2", last_synced_at: ~U[2020-05-05 12:25:17Z], locked_file_operations: false, logo: nil, main_color: "#28cb87", name: "ad-m/test-accent", operations: #Ecto.Association.NotLoaded<association :operations is not loaded>, reviewed_count: :not_loaded, revisions: #Ecto.Association.NotLoaded<association :revisions is not loaded>, target_revisions: #Ecto.Association.NotLoaded<association :target_revisions is not loaded>, translations_count: :not_loaded, updated_at: ~U[2020-05-05 12:25:17.000000Z], versions: #Ecto.Association.NotLoaded<association :versions is not loaded>}, user: %Accent.User{__meta__: #Ecto.Schema.Metadata<:loaded, "users">, access_tokens: #Ecto.Association.NotLoaded<association :access_tokens is not loaded>, auth_providers: #Ecto.Association.NotLoaded<association :auth_providers is not loaded>, bot: true, collaboration_assigns: #Ecto.Association.NotLoaded<association :collaboration_assigns is not loaded>, collaborations: #Ecto.Association.NotLoaded<association :collaborations is not loaded>, email: nil, fullname: "API Client", id: "628e51a3-8727-4249-adf8-20b063db8ac0", inserted_at: ~U[2020-05-05 11:25:55.000000Z], permissions: %{"dfa929d1-fd8c-4451-a00d-aaaffa63f825" => "bot"}, picture_url: nil, updated_at: ~U[2020-05-05 11:25:55.000000Z]}}]}
accent         | State: :ok
```
How can I provide more detailed information?

Greetings,

### PR DESCRIPTION
**Pull request by simonprev**
`top_of_the_file_comment` and `header` are only used in Gettext format and the only real-world testing was with a Gettext file.

I will refactor this when the ARB format is merged with the unified `meta` field for document. It should be standard across formats.

Closes #177

### CODE REVIEW

File: lib/hook/consumers/github/sync.ex [hunk 1]
```diff
@@ -52,8 +52,8 @@ defmodule Accent.Hook.Consumers.GitHub.Sync do
         assigns: %{
           document: document,
           document_update: %{
-            top_of_the_file_comment: parsed_document.top_of_the_file_comment,
-            header: parsed_document.header
+            top_of_the_file_comment: parsed_document && parsed_document.top_of_the_file_comment,
```
Comment (romarickb) [inline lib/hook/consumers/github/sync.ex:55]: maybe we could have something like 
```elixir
document_update: document_update(parsed_document)
....

defp document_update(nil) do
  # And maybe il will make more sense just to return nil instead of a map with nil values ?
  %{top_of_the_file_comment: nil, header: nil}
end
defp document_update(parsed_document) do
  %{top_of_the_file_comment: parsed_document.top_of_the_file_comment, header: parsed_document.header}
end
```
